run_name:
  "volvo_onTheFly_new_GECO_lagrange_exp2"
project_name:
  "HVAEFri"
entity:
  "loughborough_project"
device:
  "gpu"
device_name:
  "cuda:0"
latent_dim:
  6
beta:
  6.
batch_size:
  10
num_samples:
  16
momentum:
  0.00001
epochs:
  110
learning_rate:
  0.0001
pos_weight: 
  []
lossType: # "crossEntropy" or "Dice"
  "crossEntropy"
datasetConfig:
    input_img_dim: [256,256]
    "reducedCategories": True
    cityscapesRootPath: ""
    mapillaryRootPath: ""
    RSCDRootPath: ""
    ACDCRootPath: ""
    volvoRootPath: "../../datasets/VolvoAnnotatedImages/rawDataset/images"
    RSCD_cat: ["ice", "fresh_snow", "dry_gravel", "wet_asphalt_severe", "dry_asphalt_severe"]
    MapillSubsample: 1.
pretrained:
    enable: False
    which_model: "best"
    model_add: "./checkpoints/HVAEFri_RSCD"
continue_tra:
    enable: False
    wandb_id: "8p877guj"
    which_model: "best"
customized_GECO:
    enable: True
    goal_fri: 0.03
    goal_seg: 1.8
    alpha: 0.85
    beta: 0.85
    step_size: 0.01
    lambda_s: 1.0
    lambda_f: 1.0
    speedup: 10
    beta_min: 0.00000000001
    beta_max: 100000000000
GECO:
    enable: True
    goal_seg: 5.2
    goal_fri: 0.001
    step_size: 0.0001
    alpha: 0.7
    speedup: 100
    beta_init: 1.